- spec/RequestSequenceRepresentation.yaml
> Change from POST to GET on Representation Layer

- spec/RequestSequenceRepresentation.yaml
> Remove parameters at representationRequests

- spec/RequestSequenceRepresentation+config.json
- spec/RequestSequenceRepresentation+forwardings.yaml
> Delete wrong management in FC

- spec/RequestSequenceRepresentation+config.json
- spec/RequestSequenceRepresentation+forwardings.yaml
> Remove /docs from ServiceRequestCausesLoggingReque

- spec/RequestSequenceRepresentation+config.json
- spec/RequestSequenceRepresentation+forwardings.yaml
> Correct output of rsr-1-0-0-op-fc-is-001

- impl/server/controllers/IndividualServices.js
- impl/server/service/IndividualServicesService.js
- impl/server/service/individualServices/ForwardingAutomationServiceWithResponse.js
- impl/server/service/individualServices/PrepareForwardingAutomation.js
> To implement the individual service /v1/update-flow-visualization-page

- impl/client/package-lock.json
- impl/client/package.json
- impl/client/src/App.js
- impl/client/src/components/forms/AdvancedForm.js
- impl/client/src/components/forms/Checkbox.js
- impl/client/src/components/forms/ConditionalField.js
- impl/client/src/components/forms/Flow/FlowDiagram.js
- impl/client/src/components/forms/Flow/index.css
- impl/client/src/components/forms/FormField.js
- impl/client/src/components/forms/PasswordField.js
- impl/client/src/components/forms/RadioGroup.js
- impl/client/src/components/forms/Select.js
- impl/client/src/components/forms/TextArea.js
- impl/client/src/components/forms/TextField.js
- impl/client/src/components/forms/helpers.js
- impl/client/src/components/forms/index.js
- impl/client/src/index.css
> To implement the Front End page for Representation Layer /v1/represent-flow-visualization-page

- impl/client/src/index.js
Fix https://github.com/openBackhaul/RequestSequenceRepresentation/issues/33
> Fixed flow diagram printing twice by removing restrict mode of react

- impl/client/src/App.js
- impl/client/src/components/Spinner/Spinner.css
- impl/client/src/components/Spinner/Spinner.js
- impl/client/src/components/forms/Flow/FlowDiagram.js
Fix https://github.com/openBackhaul/RequestSequenceRepresentation/issues/22
> Created a progress bar until the result is loaded

- impl/client/src/index.css
fixes overflow x-axis for diagrams
> fixed overflow x-axis for diagrams

- impl/client/src/index.css
reduced flow diagram section width
> reduced flow diagram section width

- .dockerignore
- README.md
- dockerfile
Added dockerfile for the application
> Added dockerfile for the application

- .dockerignore
- impl/.dockerignore
- impl/dockerfile
- impl/server/index.js
- impl/server/package-lock.json
- impl/server/package.json
> To implement RequestSequenceRepresentation version 1.0.1

- testing/RequestSequenceRepresentation+data.json
> Mismatch between spec/config.json and testing/data.json files

- impl/client/src/components/Footer/Footer.css
- impl/client/src/index.css
> Footer placement fixed

- impl/client/src/App.js
> code optimize

- impl/client/src/App.js
- impl/client/src/components/Header/Header.css
- impl/client/src/index.css
> made app mobile compatible

- impl/client/src/App.js
- impl/client/src/index.css
> To include EATL logs

- impl/client/src/components/forms/Flow/FlowDiagram.js
- impl/client/src/index.css
> To include flow for records with single flow

- impl/client/src/App.js
- impl/client/src/components/Footer/Footer.js
- impl/client/src/components/Header/Header.css
- impl/client/src/components/Header/Header.js
> removed logo and footer

- impl/server/database/load.json
> To update the tcp-server port in the server side CONFIG file

- impl/client/package.json
- impl/client/src/App.js
Fix: https://github.com/openBackhaul/RequestSequenceRepresentation/issues/65
> issue65: To indicate failed records with proper connector between participants

- impl/client/src/App.js
Fixes: https://github.com/openBackhaul/RequestSequenceRepresentation/issues/66
Reviewer @PrathibaJee
> Reduce the gap between request and response arrows
